name: CI React + TypeScript

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run TypeScript type check
      - name: TypeScript type check
        run: npm run type-check

      # Run ESLint
      - name: Run ESLint
        run: npm run lint

      # Run tests
      - name: Run tests
        run: npm test -- --watchAll=false

      # Build project
      - name: Build project
        run: npm run build
